### ISSUE TITLE
Todo 문자열 응답하기

### ISSUE THREAD

**Issue by enh1535** [enh1535/practice-repository#6]
### 만들고자 하는 기능이 무엇인가요?
Todo 문자열 응답하기

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] Spring 프로젝트 생성
2. [x] Controller 클래스 생성
3. [x] 문자열 출력
4. [x] 서버 Request 확인

### 예상 작업 시간
30min
